### ISSUE TITLE
Add More AddOns to APMO

### ISSUE THREAD

**Issue by TPS** [Pale-Moon-Addons-Team/phoebus#13]
- [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker/releases): multiple releases for Pale Moon (& SeaMonkey), but separate from main Ff due to back-end compatibility work → [Privacy & Security](https://addons.palemoon.org/extensions/privacy-and-security/)
-  [AdGuard](https://github.com/AdguardTeam/AdguardBrowserExtension/releases): @AdguardTeam tailor-builds for "Old firefox versions (includes Palemoon)" :grimacing: → [Privacy & Security](https://addons.palemoon.org/extensions/privacy-and-security/)
-  [SortExceptions](https://github.com/TPS/SortExceptions): works perfectly as is, AFAICT, but _could_ be enhanced with _more_ recognized domain-lists (e.g., [ForceTLS](http://forcetls.sidstamm.com/)'s) → [Privacy & Security](https://addons.palemoon.org/extensions/privacy-and-security/) or [Appearance](https://addons.palemoon.org/extensions/appearance/)?
- [Click to Play per-element (PM)](https://github.com/2k1dmg/click-to-play-per-element-pm/releases/): @LimboSlam's [suggestion](#issuecomment-222338917) → [Privacy & Security](https://addons.palemoon.org/extensions/privacy-and-security/) or [Appearance](https://addons.palemoon.org/extensions/appearance/)?
- [JSView](https://github.com/TPS/JSView): works perfectly as is, AFAICT → [Web Development](https://addons.palemoon.org/extensions/web-development/)
- [Auto-Sort Bookmarks](https://github.com/antoyo/auto-sort-bookmarks/wiki/Information-for-future-mainteners#palemoon-version): contains a plea from @antoyo (the dev) for the PM-specific build to be included on APMO → [Appearance](https://addons.palemoon.org/extensions/appearance/) or [Other](https://addons.palemoon.org/extensions/other/)?

Based on https://github.com/Pale-Moon-Addons-Team/phoebus/commit/90aff7ad61156d43a86bbd830a5a085fa6a2b0e7, I believe this is the right place.  Else, let me know where/how to proceed. _(This supersedes ~~https://github.com/MoonchildProductions/Pale-Moon/issues/411~~.)_

**Comment by LimboSlam** [comment]
Could we please add click to play per-element by 2k1dmg: https://github.com/2k1dmg/click-to-play-per-element-pm/releases/. Should I contact him and see what he thinks?

**Comment by TPS** [comment]
Hey, @2k1dmg, what do you think? (:wink: @LimboSlam) & place it in https://addons.palemoon.org/extensions/privacy-and-security/ or https://addons.palemoon.org/extensions/appearance/?

**Comment by TPS** [comment]
@mattatobin To follow-up on ~~https://github.com/MoonchildProductions/Pale-Moon/issues/411~~/[this](#), what _is_ required to get addons listed on APMO?  I (apparently, mistakenly) added you & @wolfbeast to the repos I've control over (listed above, as well), thinking that would be a logical, necessary next step, so that's not correct, but what is?

**Comment by mattatobin** [comment]
Please clairfy exactly what you are wanting to accomplish here because I am not entirely sure I am getting the whole picture.. BUT from what I do gather it is something about Pseudo-Statics of some of your favorite extensions.. If that IS the case then:

We are not accepting mere Pseudo-Statics at this stage due to the potential legal ramifications. If you would like to fork these extensions proper with new branding and GUID according to their code licences we would be happy to add them to the site.

Additionally, please remove me from your repos and if you would like to personally add me please ask before hand otherwise it looks like spam and will result in a _personal_ block.

Also, the phoebus repo issue system is not intended to be used in this manor but merely for transparency. Issues regarding the add-ons site should be directed to the forums under the correct board and communication should use the forums PM system.
