### ISSUE TITLE
Syncing add-ons grabs incorrect versions from AMO

### ISSUE THREAD

**Issue by wolfbeast** [Pale-Moon-Addons-Team/phoebus#17]
Posting this issue here because I think it's a problem with either a limitation of AMO or the request forwarding.

When setting up Sync with synchronizing add-ons, the browser will be given the latest versions of synced add-ons instead of compatible ones. This is a problem because it obviously breaks many extensions if they are synced in Pale Moon.

**Comment by mattatobin** [comment]
I need to know how and what mechanism Sync obtains these add-ons in order to account for it.

**Comment by mattatobin** [comment]
On the basis of the it using extensions.getAddons.get.url I have checked this URL out and it seems the AMO API for this specific type of query no longer responds or obeys applicationVersion.. The normal search results still present applicationVersion targeted results but extensions.getAddons.get.url doesn't.

There are a few directions we can go to..

1. Remove the feature from Sync.

2. TRY and exploit the update checker and manipulate a response built and sent to the client. Though I resist this option because I would need to make a server connection on the server it's self and repeated bombardment could get our server blacklisted for abuse.

3. Only support Pale Moon extensions for sync. This could be combined with number 2 as well.. But again, that would expose multiple requests from our server to AMO and I resist that.

**Comment by mattatobin** [comment]
For the time being I have set the response to:
`<?xml version="1.0" encoding="utf-8" ?>
<searchresults total_results="0">
</searchresults>`

Which is no match. No Add-ons is better than broken ones until we decide what to do about it.

**Comment by wolfbeast** [comment]
I think AMO must have removed this bit along with Sync 1.1 server support. Either that or nobody at Mozilla ever expects people who Sync add-ons to get anything but the latest version because everyone uses the latest Firefox anyway, always, right? And all extensions these days are always compatible with all OSes anyway (no more binary components).

Extensions aren't being rejected upon install because Sync does not go through XPI installation the normal way, since it is assumed that proper checks are already performed server-side as far as compatible OS, compatible version, etc. is concerned. What you end up with is a list of add-ons that aren't specifically broken, but they are disabled because they are the wrong versions for the browser.

We'll have to disable this in the sync client _for the time being_ (but leave the empty thing in place because this also impacts older versions of our browser...); I'll take care of that as I'm working on Sync now anyway to fix it up for release. 

The logic on the server-side should be fairly simple to serve the correct add-on, but we can obviously not rely on AMO to do this properly - so I guess only your choice 3 is viable if we want to have this in Pale Moon Sync in the future.

> There are also indications that the current AMO API is going to end up deprecated and possibly removed in the future to be rewritten to give out JSON responses and some bits require api keys.

We should probably migrate away from using AMO completely, if this is the case. Put the mirror that was pulled into effect on our own hosting and be done with it.

**Comment by mattatobin** [comment]
The mirror is a little less than a year out of date. I could attempt one more scan but the list of valid extensions has diminished. It will take some time to do. I would also like to get the primary phoebus application done before start work again on the mirror.

**Comment by wolfbeast** [comment]
Of course. I wasn't saying "right now"
