### ISSUE TITLE
Add-ons Manager Internal Integration sends 24.9 to AMO

### ISSUE THREAD

**Issue by JustOff** [Pale-Moon-Addons-Team/phoebus#24]
Currently [components/integration](https://github.com/Pale-Moon-Addons-Team/phoebus/blob/TRUNK/phoebus/components/integration/integration.php) always uses 24.9 when dealing with AMO. Instead it should use version based on client (24.9 or 27.9). Or at least 27.9 should be the default.

**Comment by mattatobin** [comment]
extensions.getAddons.search.url's request can be made conditional because the browser sends the current version..

However, extensions.getAddons.recommended.url's request does not send the browser version thus there is no way to determine what version should be sent to AMO.

We have to keep 25 and 26 compatibility so a simple bump isn't enough.

**Comment by JustOff** [comment]
I don't yet understand Phoebus logic well, but if we could have correct search results from Add-ons Manager and following 'See all results' link, it would be already very good.

I hope that at least for this year we will be able to use AMO, but yes, it's becoming less and less relevant.

**Comment by mattatobin** [comment]
Internal recommended seems to have no exposed UI any longer so I am going to send a blank response. As for the other consumers of the Hard Coded Firefox version.. Those have been fixed and respond normally for both 27+ and <26.

I will uplift this change to RELEASE because it is important.

**Comment by JustOff** [comment]
Thanks.
