### ISSUE TITLE
Allow Add-ons to be installed from category pages

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/phoebus#35]
A significant number of users would like to be able to install add-ons from category pages. Initially, this was not permitted because of initial limitations in CMSMS but even as those were overcame and with the advent of Phoebus this was still not permitted because users SHOULD read the add-on's page for potential important information.

HOWEVER, it is a well known fact that users who won't read.. won't read regardless. So, we should allow add-ons to be installed from the category pages as to not punish those users who know exactly what they are looking for and want to get in and out quickly.

I am still on the fence about it but it is what the community wants so further input is requested.

@wolfbeast @Lootyhoof @agilbertson1977

**Comment by agilbertson1977** [comment]
I'm going to say "NO" on this one, at least for now - but I want to make clear that I'm not entirely against the concept. See below for my nuanced take on it.

If we can handle it on a case by case basis (a very BIG if, right now, I know), then we should probably allow most add-ons to be added from category pages.  Certainly language packs and search engines don't post a big problem - I guess it possible to accidentally click on the wrong language, but hopefully that mistake will get realized and corrected quite easily and quickly.  And most extensions don't have a major impact on how the browser behaves.

But for things that make significant changes to browser functionality, such as Pentadactyl, we definitely should NOT be allowing installation without AT LEAST forcing the opportunity to look at the description. This will at least slow down the users who decide to install every extension "just to see what would happen" and then claim that "the Pale Moon Add-Ons site can break the browser!" because they didn't read the description for an extension that makes extensive changes.

So I'd say to put this one on a pile marked "we'll come back to this idea after Phoebus 2.0 gets us SQL and self-service".

**Comment by wolfbeast** [comment]
No. I'm adamantly against this kind of shortcut allowing people to bypass essential information.

Because of the simple fact that the people who aren't patient enough to click through one more time and actually get ALL relevant data pertaining to the extension presented to them are going to cause a massive support load, and then justify themselves by (rightfully) saying that they were never told about this-or-that.

I also don't agree with a case-by-case basis. We should treat the installation procedure of all extensions equal and unambiguously so.

**Installing an extension to the browser is not something you do many times a day, or even daily... or weekly. It will change the way the browser works, so information about this change MUST be presented and MUST NOT be circumvented with a shortcut.**

If people think they need these shortcuts because they install the same extension over and over, then they should look into corporate setups with internal distribution/local configuration.
